"""Generate iOS apple-touch-startup-image splash PNGs from icon-512."""
from PIL import Image

BG = (10, 10, 10)
icon_full = Image.open("/home/cdub/projects/mesh-chat/static/icon-512.png").convert("RGBA")

# (width_px, height_px, css_device_width, css_device_height, device_pixel_ratio)
devices = [
    (750, 1334, 375, 667, 2),   # iPhone SE 2/3, 6/6s/7/8
    (828, 1792, 414, 896, 2),   # iPhone XR, 11
    (1125, 2436, 375, 812, 3),  # iPhone X, XS, 11 Pro
    (1242, 2688, 414, 896, 3),  # iPhone XS Max, 11 Pro Max
    (1170, 2532, 390, 844, 3),  # iPhone 12, 12 Pro, 13, 13 Pro, 14
    (1179, 2556, 393, 852, 3),  # iPhone 14 Pro, 15, 15 Pro, 16
    (1284, 2778, 428, 926, 3),  # iPhone 12 Pro Max, 13 Pro Max, 14 Plus
    (1290, 2796, 430, 932, 3),  # iPhone 14 Pro Max, 15 Plus, 15 Pro Max
]

print("<!-- b3q.44 iOS splash images. Generated by /tmp/meshchat-splash.py. -->")
for w, h, dw, dh, dpr in devices:
    canvas = Image.new("RGB", (w, h), BG)
    target = min(w, h) // 4
    ic = icon_full.resize((target, target), Image.LANCZOS)
    canvas.paste(ic, ((w - target) // 2, (h - target) // 2), ic)
    out = f"/home/cdub/projects/mesh-chat/static/splash/apple-splash-{w}x{h}.png"
    canvas.save(out, "PNG", optimize=True)
    media = (
        f"(device-width: {dw}px) and (device-height: {dh}px) "
        f"and (-webkit-device-pixel-ratio: {dpr}) and (orientation: portrait)"
    )
    print(
        f'<link rel="apple-touch-startup-image" media="{media}" '
        f'href="/splash/apple-splash-{w}x{h}.png" />'
    )
